--  EXTENSIONS AND TYPES

CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TYPE release_type AS ENUM ('ALBUM', 'SINGLE');
CREATE TYPE media_type AS ENUM ('SONG', 'EPISODE', 'AD');


--  LOOKUP TABLES

CREATE TABLE languages (
    language_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE countries (
    country_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE device_types (
    device_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);


--  USERS AND SUBSCRIPTIONS

CREATE TABLE users (
    user_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(32) NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    date_of_birth DATE NOT NULL,
    registration_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    country_id INT NOT NULL,

    CONSTRAINT fk_users_countries
        FOREIGN KEY (country_id)
        REFERENCES countries (country_id),

    CONSTRAINT chk_users_email_format
        CHECK (email LIKE '%_@_%._%')
);

CREATE TABLE subscription_types (
    subscription_type_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    price NUMERIC(10, 2) NOT NULL,
    duration_months INT NOT NULL,

    CONSTRAINT chk_subscription_types_price
        CHECK (price >= 0),

    CONSTRAINT chk_subscription_types_duration_months
        CHECK (duration_months > 0)
);

CREATE TABLE user_subscriptions (
    user_subscription_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date DATE NOT NULL DEFAULT CURRENT_DATE,
    end_date DATE NOT NULL,
    user_id INT NOT NULL,
    subscription_type_id INT NOT NULL,

    CONSTRAINT fk_user_subscriptions_users
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_user_subscriptions_subscription_types
        FOREIGN KEY (subscription_type_id)
        REFERENCES subscription_types (subscription_type_id),

    CONSTRAINT ex_user_subscriptions_no_overlap
        EXCLUDE USING gist (
            user_id                         WITH =,
            daterange(start_date, end_date) WITH &&
        )
);

CREATE INDEX idx_user_subscriptions_user_id ON user_subscriptions (user_id);


--  MUSIC

CREATE TABLE labels (
    label_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    contact_email TEXT NOT NULL,
    country_id INT NOT NULL,

    CONSTRAINT fk_labels_countries
        FOREIGN KEY (country_id)
        REFERENCES countries (country_id),

    CONSTRAINT chk_labels_contact_email_format
        CHECK (contact_email LIKE '%_@_%._%')
);

CREATE TABLE genres (
    genre_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    popularity_from_year INT NOT NULL,
    popularity_to_year INT NOT NULL,

    CONSTRAINT chk_genres_popularity_range
        CHECK (popularity_from_year <= popularity_to_year)
);

CREATE TABLE producers (
    producer_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    country_id INT NOT NULL,

    CONSTRAINT fk_producers_countries
        FOREIGN KEY (country_id)
        REFERENCES countries (country_id)
);

CREATE TABLE artists (
    artist_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    country_id INT NOT NULL,
    label_id INT,

    CONSTRAINT fk_artists_countries
        FOREIGN KEY (country_id)
        REFERENCES countries (country_id),

    CONSTRAINT fk_artists_labels
        FOREIGN KEY (label_id)
        REFERENCES labels (label_id)
        ON DELETE SET NULL
);

CREATE INDEX idx_artists_label_id ON artists (label_id);

CREATE TABLE albums (
    album_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    release_date TIMESTAMPTZ,
    release_type release_type NOT NULL
);

CREATE TABLE songs (
    song_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    duration_seconds INT NOT NULL,
    is_explicit BOOLEAN NOT NULL DEFAULT FALSE,
    release_date TIMESTAMPTZ,
    album_id INT,
    genre_id INT,
    producer_id INT NOT NULL,
    stream_count INT NOT NULL DEFAULT 0,

    CONSTRAINT chk_songs_duration_seconds
        CHECK (duration_seconds > 0),

    CONSTRAINT chk_songs_stream_count
        CHECK (stream_count >= 0),

    CONSTRAINT fk_songs_albums
        FOREIGN KEY (album_id)
        REFERENCES albums (album_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_songs_genres
        FOREIGN KEY (genre_id)
        REFERENCES genres (genre_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_songs_producers
        FOREIGN KEY (producer_id)
        REFERENCES producers (producer_id)
);

CREATE INDEX idx_songs_album_id ON songs (album_id);
CREATE INDEX idx_songs_genre_id ON songs (genre_id);

CREATE TABLE song_creators (
    song_id INT NOT NULL,
    artist_id INT NOT NULL,

    PRIMARY KEY (song_id, artist_id),

    CONSTRAINT fk_song_creators_songs
        FOREIGN KEY (song_id)
        REFERENCES songs (song_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_song_creators_artists
        FOREIGN KEY (artist_id)
        REFERENCES artists (artist_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_song_creators_artist_id ON song_creators (artist_id);

CREATE TABLE album_creators (
    album_id INT NOT NULL,
    artist_id INT NOT NULL,

    PRIMARY KEY (album_id, artist_id),

    CONSTRAINT fk_album_creators_albums
        FOREIGN KEY (album_id)
        REFERENCES albums (album_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_album_creators_artists
        FOREIGN KEY (artist_id)
        REFERENCES artists (artist_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_album_creators_artist_id ON album_creators (artist_id);


--  PODCASTS

CREATE TABLE podcast_categories (
    category_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE
);

CREATE TABLE podcasts (
    podcast_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category_id INT,
    language_id INT,
    episode_count INT NOT NULL DEFAULT 0,

    CONSTRAINT chk_podcasts_episode_count
        CHECK (episode_count >= 0),

    CONSTRAINT fk_podcasts_podcast_categories
        FOREIGN KEY (category_id)
        REFERENCES podcast_categories (category_id)
        ON DELETE SET NULL,

    CONSTRAINT fk_podcasts_languages
        FOREIGN KEY (language_id)
        REFERENCES languages (language_id)
        ON DELETE SET NULL
);

CREATE TABLE podcast_episodes (
    episode_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    duration_seconds INT NOT NULL,
    release_date TIMESTAMPTZ,
    podcast_id INT NOT NULL,
    stream_count INT NOT NULL DEFAULT 0,

    CONSTRAINT chk_podcast_episodes_duration_seconds
        CHECK (duration_seconds > 0),

    CONSTRAINT chk_podcast_episodes_stream_count
        CHECK (stream_count >= 0),

    CONSTRAINT fk_podcast_episodes_podcasts
        FOREIGN KEY (podcast_id)
        REFERENCES podcasts (podcast_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_podcast_episodes_podcast_id ON podcast_episodes (podcast_id);


--  ADVERTISING

CREATE TABLE advertisers (
    advertiser_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    country_id INT NOT NULL,

    CONSTRAINT fk_advertisers_countries
        FOREIGN KEY (country_id)
        REFERENCES countries (country_id)
);

CREATE TABLE ads (
    ad_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    duration_seconds INT NOT NULL,
    advertiser_id INT NOT NULL,
    stream_count INT NOT NULL DEFAULT 0,

    CONSTRAINT chk_ads_duration_seconds
        CHECK (duration_seconds > 0),

    CONSTRAINT chk_ads_stream_count
        CHECK (stream_count >= 0),

    CONSTRAINT fk_ads_advertisers
        FOREIGN KEY (advertiser_id)
        REFERENCES advertisers (advertiser_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_ads_advertiser_id ON ads (advertiser_id);


--  FOLLOWS AND LIKES

CREATE TABLE follows_artists (
    user_id INT NOT NULL,
    artist_id INT NOT NULL,
    follow_date TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, artist_id),

    CONSTRAINT fk_follows_artists_users
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_follows_artists_artists
        FOREIGN KEY (artist_id)
        REFERENCES artists (artist_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_follows_artists_artist_id ON follows_artists (artist_id);

CREATE TABLE follows_podcasts (
    user_id INT NOT NULL,
    podcast_id INT NOT NULL,
    follow_date TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, podcast_id),

    CONSTRAINT fk_follows_podcasts_users
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_follows_podcasts_podcasts
        FOREIGN KEY (podcast_id)
        REFERENCES podcasts (podcast_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_follows_podcasts_podcast_id ON follows_podcasts (podcast_id);

CREATE TABLE song_likes (
    user_id INT NOT NULL,
    song_id INT NOT NULL,
    like_date TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, song_id),

    CONSTRAINT fk_song_likes_users
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_song_likes_songs
        FOREIGN KEY (song_id)
        REFERENCES songs (song_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_song_likes_song_id ON song_likes (song_id);

CREATE TABLE episode_likes (
    user_id INT NOT NULL,
    episode_id INT NOT NULL,
    like_date TIMESTAMPTZ NOT NULL DEFAULT now(),

    PRIMARY KEY (user_id, episode_id),

    CONSTRAINT fk_episode_likes_users
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_episode_likes_podcast_episodes
        FOREIGN KEY (episode_id)
        REFERENCES podcast_episodes (episode_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_episode_likes_episode_id ON episode_likes (episode_id);


--  PLAYBACK HISTORY

CREATE TABLE playback_history (
    playback_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playback_date TIMESTAMPTZ NOT NULL DEFAULT now(),
    duration_played_seconds INT NOT NULL,
    media_type media_type NOT NULL,
    media_id INT NOT NULL,
    user_id INT NOT NULL,
    device_type_id INT NOT NULL,

    CONSTRAINT chk_playback_history_duration_played_seconds
        CHECK (duration_played_seconds >= 0),

    CONSTRAINT fk_playback_history_users
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_playback_history_device_types
        FOREIGN KEY (device_type_id)
        REFERENCES device_types (device_type_id)
);

CREATE INDEX idx_playback_history_user_id ON playback_history (user_id);
CREATE INDEX idx_playback_history_playback_date ON playback_history (playback_date);
CREATE INDEX idx_playback_history_device_type_id ON playback_history (device_type_id);

CREATE TABLE song_playback_details (
    playback_id INT PRIMARY KEY,
    song_id INT NOT NULL,

    CONSTRAINT fk_song_playback_details_playback_history
        FOREIGN KEY (playback_id)
        REFERENCES playback_history (playback_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_song_playback_details_songs
        FOREIGN KEY (song_id)
        REFERENCES songs (song_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_song_playback_details_song_id ON song_playback_details (song_id);

CREATE TABLE episode_playback_details (
    playback_id INT PRIMARY KEY,
    episode_id INT NOT NULL,

    CONSTRAINT fk_episode_playback_details_playback_history
        FOREIGN KEY (playback_id)
        REFERENCES playback_history (playback_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_episode_playback_details_podcast_episodes
        FOREIGN KEY (episode_id)
        REFERENCES podcast_episodes (episode_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_episode_playback_details_episode_id ON episode_playback_details (episode_id);

CREATE TABLE ad_playback_details (
    playback_id INT PRIMARY KEY,
    ad_id INT NOT NULL,

    CONSTRAINT fk_ad_playback_details_playback_history
        FOREIGN KEY (playback_id)
        REFERENCES playback_history (playback_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_ad_playback_details_ads
        FOREIGN KEY (ad_id)
        REFERENCES ads (ad_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_ad_playback_details_ad_id ON ad_playback_details (ad_id);
